fix: stop reason priority
eve-autonomy/autoware_state_machine pull request #5
Opened 2023-05-30 01:41 UTC by h-ohta

## Description
`/awapi/autoware/get/status` に格納されているstop_reasonにおいて、VTLとobstacle_stopが存在していてかつ両方の距離が0の場合、選択されるstop_reasonがチャタリングして音声発話にも影響が出ているため、修正を実施

修正においては、X1.eveで使用されているstop_reasonを優先度を決めて取り出せるようにした

### stop_reasonの優先度について
今回考慮すべきstop_reasonは以下の通りである

- STOP_LINE
- DETECTION_AREA
- OBSTACLE_STOP
- SURROUND_OBSTACLE_CHECK
- VIRTUAL_TRAFFIC_LIGHT

結果として、優先順位判定ロジックを以下の通りとする

1. 距離が両方とも0の場合
    1. SURROUND_OBSTACLE_CHECK
    2. OBSTACLE_STOP
    3. DETECTION_AREA
    4. VIRTUAL_TRAFFIC_LIGHT
    5. STOP_LINE 
2. 距離がより近い方を選択

### 参考：音声発話の優先順位
https://app.box.com/file/860109836014?s=9ss1fizbo587ecaqyz6r7llo1cak21j6

## Related Links
https://tier4.atlassian.net/browse/AEAP-560

## Tests Performed
上記チケットにて確認

2023-05-30 01:42 UTC, h-ohta commented on src/autoware_state_machine.cpp
> -     * Since it is a Float expression, the epsilon value is used because the matching comparison of 0 values is not valid. */
複数の「StopReasons」データが配列に格納されます。状況に応じてその都度格納順が変わります。
     最後に、最も優先度の高い「StopReason」データを 1 つに絞り込みます。
     判定の流れは以下の通り
       ・「SurrondObstacleCheck」を最優先でチェックしてください。
         「SurrondObstacleCheck」では、すでに物体が接近しているため、距離情報「dist_to_stop_pose」は評価されません。
       ・その他の「StopReason」は距離情報「dist_to_stop_pose」が小さいものが優先されます。
     ※Float式なので0値の一致比較は無効なのでイプシロン値を使用します。

2023-05-30 02:02 UTC, h-ohta commented on src/autoware_state_machine.cpp
> +      // 4. 距離が近い
今回考慮すべきstop_reasonは以下の通り
```
string STOP_LINE=StopLine
string DETECTION_AREA=DetectionArea
string OBSTACLE_STOP=ObstacleStop
string SURROUND_OBSTACLE_CHECK=SurroundObstacleCheck
string VIRTUAL_TRAFFIC_LIGHT=VirtualTrafficLight
```

この内、優先順位をつけるべきはこれ移行の判定および音声発話で使用されている、以下の３つ
- SURROUND_OBSTACLE_CHECK
- OBSTACLE_STOP
- DETECTION_AREA

残りの２つについては順番が狂っても音声発話には影響がない

2023-05-30 06:00 UTC, h-ohta commented
コメントアウトはPRマージ手前に削除する

2023-05-30 07:20 UTC, yn-mrse commented on src/autoware_state_machine.cpp
> +    };
https://eva.box.com/s/9ss1fizbo587ecaqyz6r7llo1cak21j6 要求仕様と同一順であることを確認。OK

2023-05-30 07:25 UTC, h-ohta commented on src/autoware_state_machine.cpp
> +  // RCLCPP_INFO(this->get_logger(), "final stop_reason: %s, distance: %lf", stop_reason_.c_str(), cur_dist_to_stop_pose_);
PR作成マージ前に削除

2023-05-30 07:25 UTC, h-ohta commented on src/autoware_state_machine.cpp
> +  // }
PRマージ前に削除

2023-05-30 08:14 UTC, h-ohta commented on src/autoware_state_machine.cpp
> +  // RCLCPP_INFO(this->get_logger(), "final stop_reason: %s, distance: %lf", stop_reason_.c_str(), cur_dist_to_stop_pose_);
```suggestion
  // RCLCPP_INFO(this->get_logger(), "final stop_reason: %s, distance: %lf", stop_reason_.c_str(), cur_dist_to_stop_pose_);
```

2023-06-05 03:38 UTC, yn-mrse requested changes

2023-06-05 03:38 UTC, yn-mrse commented on include/autoware_state_machine/autoware_state_machine.hpp
> +  std::pair<std::string, double> getNearestStopReason(
関数内処理で距離以外の優先度も扱うので、それがわかる命名としたいです。
例えば下記のような命名でいかがでしょう？
```suggestion
  std::pair<std::string, double> getNearestStopReasonWithPriority(
```

2023-06-05 04:16 UTC, h-ohta commented on include/autoware_state_machine/autoware_state_machine.hpp
> +  std::pair<std::string, double> getNearestStopReason(
修正しました

2023-06-05 04:27 UTC, yn-mrse commented on src/autoware_state_machine.cpp
> +      const double ERROR = 1e-3;
こちらはもともと [`constexpr double double_epsilon = std::numeric_limits<double>::epsilon();`](https://github.com/eve-autonomy/autoware_state_machine/pull/5/files#diff-0977aa4eb0fda7b15eb375bdd01d401c873e9738e0c123e4c8fbac97376c456dL29) で定義していた箇所の置き替えになると思いますが、障害物検知時の計測誤差を意図していますでしょうか？

2023-06-05 04:34 UTC, h-ohta commented on src/autoware_state_machine.cpp
> +      const double ERROR = 1e-3;
distanceがどれくらいの精度を持っているかわからなかったので、epsilonで見ると0mである判定が難しいのかなと思っています。その上で1e-3（1mm）は精度的に難しいからそれより下の場合はすべて0にする形にするのがいいのではと思って今の実装にしています

2023-06-05 06:06 UTC, yn-mrse approved these changes

2023-06-05 06:53 UTC, merged